### ISSUE TITLE
Version library

### ISSUE THREAD

**Issue by lightsun1323** [expanseElectronics/artnetnodes#5]
Hello
Thank you very much for your complete project, I only encountered one problem, that is not having the version of the libraries that you used for the project and also the version of esp8266 that you installed for your Arduino.

Regards
Sami

**Comment by LoneWalkerWolf** [comment]
Hello! 

Apologies for the late reply, we've been busy working on new products!
Please find versions of every library below. 

1. ArduinoJson (Benoit Blanchon) - V5.13.5
2. Functional-Vlpp (Khoi Hoang) - V1.0.2

Use ESP8266 Board Version 2.7.3 (latest version should work, but 2.7.3 is our recommended version. 

Thanks.
